fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    stdmod: "git://github.com/stdmod/stdmod.git"
    nginx: "https://github.com/netmanagers/puppet-nginx.git"
    apache: "https://github.com/example42/puppet-apache"
    php5fpm: "https://github.com/zertico/puppet-php5fpm.git"	
    puppi:  "https://github.com/example42/puppi" 
  symlinks:
    deploy_php: "#{source_dir}"
